[package]
name = "dot"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
softbuffer = "0.4.3"
tiny-skia = "0.11.4"
winit = "0.30.0"
